HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xaaffcd10>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1e83d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb17ee330>: Failed to establish a new connection: [Errno 111] Connection refused'))
